 
 - name: Install Ingress Controller
   command: kubectl apply -f https://raw.githubusercontent.com/haproxytech/kubernetes-ingress/v1.5/deploy/haproxy-ingress.yaml
   become: yes

 - name: Create namespaces for Ingress
   command: kubectl get pods --namespace=haproxy-controller
   become: yes
