---

- name: Set timezone to Europe/Madrid
  timezone:
    name: Europe/Madrid
  become: yes

- name: install chronyd
  dnf:
    name: chronyd
    state: absent
  become: yes

- name: Ensure chronyd is active
  service:
    name: chronyd
    state: started
  become: yes
