---

- name: Configuration Master Node
  hosts: all
  vars_files:
    - "group_vars/configuration-master.yaml"
    - "group_vars/create-kubeadmin.yaml"
  gather_facts: true
  
  roles:
    - configuration-master
